"""Typed, non-destructive PACS adapter boundary."""

from typing import Protocol

from app.pacs.schemas import PacsHealth, PacsStudyMetadata, StoreResult


class PacsAdapter(Protocol):
    def health(self) -> PacsHealth: ...

    def list_studies(self) -> list[PacsStudyMetadata]: ...

    def find_study(self, study_instance_uid: str) -> list[PacsStudyMetadata]: ...

    def get_study_tags(self, orthanc_study_id: str) -> dict[str, dict[str, str]]: ...

    def list_series(self, orthanc_study_id: str) -> list[dict[str, object]]: ...

    def render_instance_preview(self, orthanc_instance_id: str) -> tuple[bytes, str]: ...

    def upload_instance(self, dicom_bytes: bytes) -> str: ...

    def send_study(self, orthanc_study_id: str, destination_name: str) -> StoreResult: ...
