"""Print/PDF rendering of finalized reports using fpdf2.

The PDF is generated on demand from persisted authored text only. It contains
no patient identifiers beyond the synthetic accession, carries the synthetic
disclaimer on every page, and is audited like every other export path.
"""

import uuid
from io import BytesIO

from fpdf import FPDF
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.audit.service import AuditActor, append_audit_event
from app.imaging.models import (
    RadiologyReport,
    ReportStatus,
)


class PrintExportError(Exception):
    """Expected print export failure."""

    def __init__(self, detail: str, *, status_code: int = 409) -> None:
        super().__init__(detail)
        self.detail = detail
        self.status_code = status_code


DISCLAIMER = (
    "SYNTHETIC PORTFOLIO DEMONSTRATION - NOT A REAL MEDICAL DOCUMENT. "
    "Generated by Radiology Operations Copilot from human-authored text."
)


def _latin1_safe(text: str) -> str:
    """Map any character Helvetica cannot render to a close ASCII form."""
    replacements = {"—": "-", "–": "-", "·": "-", "’": "'", "“": '"', "”": '"'}
    replaced = text
    for source, target in replacements.items():
        replaced = replaced.replace(source, target)
    return replaced.encode("latin-1", "replace").decode("latin-1")


def render_report_pdf(session: Session, *, report: RadiologyReport) -> bytes:
    """Render a finalized report to a bounded, plainly formatted PDF."""
    from app.imaging.models import RadiologyReportVersion

    versions = list(
        session.scalars(
            select(RadiologyReportVersion)
            .where(RadiologyReportVersion.report_id == report.id)
            .order_by(RadiologyReportVersion.version_number)
        )
    )
    current_version = next(
        (
            version
            for version in reversed(versions)
            if version.version_number == report.current_version_number
        ),
        None,
    )
    if current_version is None:
        raise PrintExportError("Report has no rendered content", status_code=409)

    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # Header band.
    pdf.set_font("Helvetica", "B", 15)
    pdf.cell(0, 10, "Synthetic Imaging Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(90, 90, 90)
    pdf.cell(
        0,
        6,
        _latin1_safe(
            f"Accession: {study_accession(session, report)}    "
            f"Version: {report.current_version_number}    "
            f"Status: {ReportStatus.FINALIZED.value}"
        ),
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.cell(0, 6, DISCLAIMER, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    def section(title: str, body: str) -> None:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for paragraph in body.splitlines() or [""]:
            pdf.multi_cell(0, 5.5, _latin1_safe(paragraph) or " ")
        pdf.ln(2)

    section("Indication", current_version.indication)
    section("Findings", current_version.findings)
    section("Impression", current_version.impression)

    if report.finalized_at:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(90, 90, 90)
        pdf.cell(
            0,
            6,
            _latin1_safe(
                f"Finalized by {report.finalized_by or 'unknown'} at "
                f"{report.finalized_at.isoformat()}"
            ),
            new_x="LMARGIN",
            new_y="NEXT",
        )

    return bytes(pdf.output())


def study_accession(session: Session, report: RadiologyReport) -> str:
    from app.pacs.models import PacsStudy

    study = session.get(PacsStudy, report.study_id)
    return study.accession_number if study else "UNKNOWN"


def export_report_pdf(
    session: Session,
    *,
    report_id: uuid.UUID,
    exported_by: str,
) -> tuple[bytes, RadiologyReport]:
    """Gate, render, and audit a print/PDF export."""
    report = session.get(RadiologyReport, report_id)
    if report is None:
        raise PrintExportError("Report not found", status_code=404)
    if report.status != ReportStatus.FINALIZED:
        raise PrintExportError("Only a finalized report can be printed", status_code=409)
    content = render_report_pdf(session, report=report)
    append_audit_event(
        session,
        actor=AuditActor("user", exported_by),
        action="imaging.report.print_exported",
        entity_type="radiology_report",
        entity_id=str(report.id),
        decision_reason="Print/PDF export of finalized report",
        correlation_id=f"report-{report.id}",
        request_id=f"report-{report.id}",
        success=True,
        after_state={
            "status": report.status.value,
            "version": report.current_version_number,
            "format": "pdf",
            "bytes": len(content),
        },
    )
    session.flush()
    return content, report


_ = BytesIO  # retained import marker for potential future streaming use
